Repository mihirkatare/DeepMEM, pull requests merged in 2021-10, with the labels that each got.

#16 feat: Update model architecture and multiprocessing
  README.md
  data.py
  main.py
  model.py
  networks.py
  requirements.txt
  utils.py
Labels: documentation, enhancement

#11 chore: Add linting and formatting pre-commit hooks
  .flake8
  .pre-commit-config.yaml
  README.md
  data.py
  debug/debugdata.py
  debug/debugmodel.py
  debug/fastloader.py
  dev-requirements.txt
  main.py
  model.py
  networks.py
  options.py
  pyproject.toml
  utils.py
Labels: chore

#19 docs: Add install instructions from PyPI and version control
  README.md
Labels: documentation
